variables:
  GIT_SUBMODULE_STRATEGY: normal
  CODECOV_TOKEN: "4d08d9aa-a2cc-4c5d-9511-94a89b59c3f0"

.my-script:  # script fragments
  - &linux-install-lua53 apt update && apt install -y liblua5.3-dev
  - &linux-install-lua52 apt update && apt install -y liblua5.2-dev

.linux: &linux
  script:
    # setup virtualenv
    - pip install virtualenv pipenv
    - python -mvirtualenv .venv
    - source .venv/bin/activate
    - pip install pytest pytest-cov codecov
    - python -V
    # run test
    - python setup.py develop
    - python -c "print(__import__('ffilupa').get_default_lualib().version)"   # print lua version
    - python -mpytest -vv --cov=ffilupa
    - python -mcodecov
    - deactivate
    - git clean -f
    # test normal installation
    - mkdir ../test-normal
    - cd ../test-normal
    - echo '[packages]' > Pipfile
    - echo 'ffilupa = { path = "./../ffilupa" }' >> Pipfile
    - pipenv install
    - pipenv run python -c "print(__import__('ffilupa').get_default_lualib().version)"

.linux-lua53: &linux-lua53
  <<: *linux
  before_script:
    - *linux-install-lua53

.linux-lua52: &linux-lua52
  <<: *linux
  before_script:
    - *linux-install-lua52

linux-lua53-py35:
  <<: *linux-lua53
  image: python:3.5-stretch

linux-lua53-py36:
  <<: *linux-lua53
  image: python:3.6-stretch

linux-lua53-py37:
  <<: *linux-lua53
  image: python:3.7-stretch

linux-lua52-py35:
  <<: *linux-lua52
  image: python:3.5-stretch

linux-lua52-py36:
  <<: *linux-lua52
  image: python:3.6-stretch

linux-lua52-py37:
  <<: *linux-lua52
  image: python:3.7-stretch
