language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - nightly
  - pypy
  - pypy3
install: pip install pytest pytest-cov codecov
script:
  - python setup.py develop
  - pytest -v tests.py --cov=ffilupa
  - pytest -v --doctest-modules ffilupa --cov=ffilupa --cov-append
  - pytest -v docs/start.rst --cov=ffilupa --cov-append
after_success: codecov
